### ISSUE TITLE
IMDB - Trakt sync stops midway

### ISSUE THREAD

**Issue by vinu21may** [RileyXX/IMDB-Trakt-Syncer#100]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/IMDBTraktSyncer.py", line 265, in main
    success, status_code, url = EH.get_page_with_retries(f'https://www.imdb.com/title/{item["IMDB_ID"]}/', driver, wait)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/errorHandling.py", line 124, in get_page_with_retries
    wait.until(lambda driver: driver.execute_script(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/errorHandling.py", line 124, in <lambda>
    wait.until(lambda driver: driver.execute_script(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.127)
Stacktrace:
0   chromedriver_mac-arm64              0x0000000100763a38 chromedriver_mac-arm64 + 4389432
1   chromedriver_mac-arm64              0x000000010075c344 chromedriver_mac-arm64 + 4358980
2   chromedriver_mac-arm64              0x0000000100378afc chromedriver_mac-arm64 + 281340
3   chromedriver_mac-arm64              0x0000000100362154 chromedriver_mac-arm64 + 188756
4   chromedriver_mac-arm64              0x0000000100362090 chromedriver_mac-arm64 + 188560
5   chromedriver_mac-arm64              0x00000001003f341c chromedriver_mac-arm64 + 783388
6   chromedriver_mac-arm64              0x00000001003afed0 chromedriver_mac-arm64 + 507600
7   chromedriver_mac-arm64              0x00000001003b08a8 chromedriver_mac-arm64 + 510120
8   chromedriver_mac-arm64              0x000000010072b3bc chromedriver_mac-arm64 + 4158396
9   chromedriver_mac-arm64              0x000000010072fe20 chromedriver_mac-arm64 + 4177440
10  chromedriver_mac-arm64              0x000000010071107c chromedriver_mac-arm64 + 4051068
11  chromedriver_mac-arm64              0x000000010073070c chromedriver_mac-arm64 + 4179724
12  chromedriver_mac-arm64              0x000000010070407c chromedriver_mac-arm64 + 3997820
13  chromedriver_mac-arm64              0x000000010074e0d4 chromedriver_mac-arm64 + 4301012
14  chromedriver_mac-arm64              0x000000010074e250 chromedriver_mac-arm64 + 4301392
15  chromedriver_mac-arm64              0x000000010075bf3c chromedriver_mac-arm64 + 4357948
16  libsystem_pthread.dylib             0x0000000193626f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000193621d34 thread_start + 8

--------------------------------------------------
Submit the error here: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/new?template=bug_report.yml
--------------------------------------------------
Traceback (most recent call last):
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/IMDBTraktSyncer.py", line 265, in main
    success, status_code, url = EH.get_page_with_retries(f'https://www.imdb.com/title/{item["IMDB_ID"]}/', driver, wait)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/errorHandling.py", line 124, in get_page_with_retries
    wait.until(lambda driver: driver.execute_script(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/errorHandling.py", line 124, in <lambda>
    wait.until(lambda driver: driver.execute_script(
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.127)
Stacktrace:
0   chromedriver_mac-arm64              0x0000000100763a38 chromedriver_mac-arm64 + 4389432
1   chromedriver_mac-arm64              0x000000010075c344 chromedriver_mac-arm64 + 4358980
2   chromedriver_mac-arm64              0x0000000100378afc chromedriver_mac-arm64 + 281340
3   chromedriver_mac-arm64              0x0000000100362154 chromedriver_mac-arm64 + 188756
4   chromedriver_mac-arm64              0x0000000100362090 chromedriver_mac-arm64 + 188560
5   chromedriver_mac-arm64              0x00000001003f341c chromedriver_mac-arm64 + 783388
6   chromedriver_mac-arm64              0x00000001003afed0 chromedriver_mac-arm64 + 507600
7   chromedriver_mac-arm64              0x00000001003b08a8 chromedriver_mac-arm64 + 510120
8   chromedriver_mac-arm64              0x000000010072b3bc chromedriver_mac-arm64 + 4158396
9   chromedriver_mac-arm64              0x000000010072fe20 chromedriver_mac-arm64 + 4177440
10  chromedriver_mac-arm64              0x000000010071107c chromedriver_mac-arm64 + 4051068
11  chromedriver_mac-arm64              0x000000010073070c chromedriver_mac-arm64 + 4179724
12  chromedriver_mac-arm64              0x000000010070407c chromedriver_mac-arm64 + 3997820
13  chromedriver_mac-arm64              0x000000010074e0d4 chromedriver_mac-arm64 + 4301012
14  chromedriver_mac-arm64              0x000000010074e250 chromedriver_mac-arm64 + 4301392
15  chromedriver_mac-arm64              0x000000010075bf3c chromedriver_mac-arm64 + 4357948
16  libsystem_pthread.dylib             0x0000000193626f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000193621d34 thread_start + 8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/IMDBTraktSyncer.py", line 720, in <module>
    main()
  File "/Users/vinodmenon/Downloads/pythonScripts/IMDBTraktSyncer/IMDBTraktSyncer.py", line 714, in main
    driver.close()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in close
    self.execute(Command.CLOSE)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.127)
Stacktrace:
0   chromedriver_mac-arm64              0x0000000100763a38 chromedriver_mac-arm64 + 4389432
1   chromedriver_mac-arm64              0x000000010075c344 chromedriver_mac-arm64 + 4358980
2   chromedriver_mac-arm64              0x0000000100378afc chromedriver_mac-arm64 + 281340
3   chromedriver_mac-arm64              0x0000000100360d08 chromedriver_mac-arm64 + 183560
4   chromedriver_mac-arm64              0x0000000100361c44 chromedriver_mac-arm64 + 187460
5   chromedriver_mac-arm64              0x000000010037905c chromedriver_mac-arm64 + 282716
6   chromedriver_mac-arm64              0x00000001003536a4 chromedriver_mac-arm64 + 128676
7   chromedriver_mac-arm64              0x00000001003e5ecc chromedriver_mac-arm64 + 728780
8   chromedriver_mac-arm64              0x00000001003afed0 chromedriver_mac-arm64 + 507600
9   chromedriver_mac-arm64              0x00000001003b08a8 chromedriver_mac-arm64 + 510120
10  chromedriver_mac-arm64              0x000000010072b3bc chromedriver_mac-arm64 + 4158396
11  chromedriver_mac-arm64              0x000000010072fe20 chromedriver_mac-arm64 + 4177440
12  chromedriver_mac-arm64              0x000000010071107c chromedriver_mac-arm64 + 4051068
13  chromedriver_mac-arm64              0x000000010073070c chromedriver_mac-arm64 + 4179724
14  chromedriver_mac-arm64              0x000000010070407c chromedriver_mac-arm64 + 3997820
15  chromedriver_mac-arm64              0x000000010074e0d4 chromedriver_mac-arm64 + 4301012
16  chromedriver_mac-arm64              0x000000010074e250 chromedriver_mac-arm64 + 4301392
17  chromedriver_mac-arm64              0x000000010075bf3c chromedriver_mac-arm64 + 4357948
18  libsystem_pthread.dylib             0x0000000193626f94 _pthread_start + 136
19  libsystem_pthread.dylib             0x0000000193621d34 thread_start + 8

### Environment

OS: macOS
Using pip install method: yes

### Screenshots

![Image 28-06-24 at 3 17 AM](https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/42231041/29ef6aa0-8836-4a4d-baf1-f62d929cb6b7)

**Comment by RileyXX** [comment]
Hi sorry for the late reply. Are you still having issues with this error? There were some fixes in v2.9.5 that should resolve this. If you're still having issues let me know and I can look into it. Thanks
