### ISSUE TITLE
 No such file or directory: 'python' in version 3.0.x on MacOS

### ISSUE THREAD

**Issue by CabbageMcHead** [RileyXX/IMDB-Trakt-Syncer#115]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

This might be my bad, but in MacOS I need to use "python3" and straight away the new version bombs out.  Do I need to create an alias or should it "just work" as per v2.9.5?

Starting IMDBTraktSyncer....
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/IMDBtraktsyncer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 21, in main
    from IMDBTraktSyncer import checkVersion
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/checkVersion.py", line 52, in <module>
    checkVersion()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/checkVersion.py", line 35, in checkVersion
    installed_version = get_installed_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/checkVersion.py", line 7, in get_installed_version
    result = subprocess.run(['python', '-m', 'pip', 'show', 'imdbtraktsyncer'], capture_output=True, text=True, check=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

### Environment

MacOS Sequoia 15.2

**Comment by RileyXX** [comment]
Thanks for reporting this, calling "python" without any exception or fallbacks for different python installs was an oversight on my part. I'll be adding a patch for this shortly.

**Comment by RileyXX** [comment]
This should be fixed now in [v3.0.3](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v3.0.3)

````
python -m pip install IMDBTraktSyncer
````

**Comment by RileyXX** [comment]
And to answer your question yes [v2.9.5](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v2.9.5) would have been the correct version to use in your case as that was the last version before this was changed.

**Comment by CabbageMcHead** [comment]
confirmed working in 3.0.3!
