### ISSUE TITLE
AttributeError: partially initialized module 'IMDBTraktSyncer.verifyCredentials' has no attribute 'trakt_client_id' (most likely due to a circular import)

### ISSUE THREAD

**Issue by surlebeat** [RileyXX/IMDB-Trakt-Syncer#39]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Hey there,

I wan't run the script, getting that log.
`Traceback (most recent call last):
  File "/home/michel/.local/bin/IMDBTraktSyncer", line 5, in <module>
    from IMDBTraktSyncer.IMDBTraktSyncer import main
  File "/home/michel/.local/lib/python3.10/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 16, in <module>
    from IMDBTraktSyncer import verifyCredentials as VC
  File "/home/michel/.local/lib/python3.10/site-packages/IMDBTraktSyncer/verifyCredentials.py", line 57, in <module>
    trakt_access_token = authTrakt.authenticate(client_id, client_secret)
  File "/home/michel/.local/lib/python3.10/site-packages/IMDBTraktSyncer/authTrakt.py", line 44, in authenticate
    response = EH.make_trakt_request('https://api.trakt.tv/oauth/token', payload=data)
  File "/home/michel/.local/lib/python3.10/site-packages/IMDBTraktSyncer/errorHandling.py", line 27, in make_trakt_request
    'trakt-api-key': VC.trakt_client_id,
AttributeError: partially initialized module 'IMDBTraktSyncer.verifyCredentials' has no attribute 'trakt_client_id' (most likely due to a circular import)
`
Any idea how to solve that?
Thanks !

### Environment

OS: Ubuntu 22.04.2 LTS
Python 3.10.6

Pip intallation

**Comment by RileyXX** [comment]
Hi, thanks for the detailed bug report! It looks like a circular import bug was introduced in one of the recent patches. This should be fixed now in v1.3.3. You can see the details of this patch [here](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.3.3). 

For pip install you can update to the latest version using the following:
````
python -m pip install IMDBTraktSyncer --upgrade
````
Alternatively, you can download the latest .zip from the [releases page](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases).

If you are still getting this error on the latest version let me know and I will investigate further. Thanks!

**Comment by surlebeat** [comment]
Thanks a lot for answering that fast. I managed to sync with another tool but I'll definitly give yours another try.
