### ISSUE TITLE
WebDriverException: Cannot Find Chrome Binary

### ISSUE THREAD

**Issue by MasuRii** [RileyXX/IMDB-Trakt-Syncer#65]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\IMDBTraktSyncer\IMDBTraktSyncer.py", line 63, in main
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
        GetHandleVerifier [0x00007FF7711752A2+57122]
        (No symbol) [0x00007FF7710EEA92]
        (No symbol) [0x00007FF770FBE3AB]
        (No symbol) [0x00007FF770FE4936]
        (No symbol) [0x00007FF770FE2FE1]
        (No symbol) [0x00007FF77101EA4F]
        (No symbol) [0x00007FF77101E5B0]
        (No symbol) [0x00007FF771016DB3]
        (No symbol) [0x00007FF770FED2B1]
        (No symbol) [0x00007FF770FEE494]
        GetHandleVerifier [0x00007FF77141EF82+2849794]
        GetHandleVerifier [0x00007FF771471D24+3189156]
        GetHandleVerifier [0x00007FF77146ACAF+3160367]
        GetHandleVerifier [0x00007FF771206D06+653702]
        (No symbol) [0x00007FF7710FA208]
        (No symbol) [0x00007FF7710F62C4]
        (No symbol) [0x00007FF7710F63F6]
        (No symbol) [0x00007FF7710E67A3]
        BaseThreadInitThunk [0x00007FFBA1757034+20]
        RtlUserThreadStart [0x00007FFBA3322651+33]

--------------------------------------------------

### Environment

OS: Windows 10
Using pip install method: yes
Using manual no pip install method: no

### Screenshots

![image](https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/21298898/f1ede9a0-f1ae-4f62-b773-cfa22ed28066)

**Comment by MasuRii** [comment]
Nvm got it, I look at the error and seems like it didn't find the path location of my chrome, that's because I didn't installed my chrome and it was only a portable version. So instead I just manually include it in the path environment for the location of my chrome and it works.
