### ISSUE TITLE
Trakt sign in problem

### ISSUE THREAD

**Issue by sherlockholmes77777** [RileyXX/IMDB-Trakt-Syncer#73]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Starting webdriver...
Successfully signed in to IMDB
Processing Trakt Data
   - Request failed with status code 401: Unauthorized - OAuth must be provided

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 122, in main
    trakt_watchlist, trakt_ratings, trakt_reviews, watched_content = traktData.getTraktData()
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IMDBTraktSyncer/traktData.py", line 151, in getTraktData
    json_data = json.loads(response.text)
                           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

--------------------------------------------------
Submit the error here: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/new?template=bug_report.yml
--------------------------------------------------

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

### Environment

MacOS

**Comment by sherlockholmes77777** [comment]
It was a temporary issue and it fixed by itself for now.
Thanks for the reply.
