### ISSUE TITLE
Error (disconnected: Unable to receive message from renderer)

### ISSUE THREAD

**Issue by austinarchibald** [RileyXX/IMDB-Trakt-Syncer#74]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 123, in main
    imdb_watchlist, imdb_ratings, imdb_reviews, errors_found_getting_imdb_reviews = imdbData.getImdbData(imdb_username, imdb_password, driver, directory, wait)
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/IMDBTraktSyncer/imdbData.py", line 32, in getImdbData
    success, status_code, url = EH.get_page_with_retries('https://www.imdb.com/list/watchlist', driver, wait)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/IMDBTraktSyncer/errorHandling.py", line 121, in get_page_with_retries
    driver.get(url)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 353, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=118.0.5993.117)
Stacktrace:
0   chromedriver_mac-x64                0x0000000102c1be08 chromedriver_mac-x64 + 5025288
1   chromedriver_mac-x64                0x0000000102c12c23 chromedriver_mac-x64 + 4987939
2   chromedriver_mac-x64                0x00000001027b4e67 chromedriver_mac-x64 + 409191
3   chromedriver_mac-x64                0x000000010279a740 chromedriver_mac-x64 + 300864
4   chromedriver_mac-x64                0x000000010279a4d1 chromedriver_mac-x64 + 300241
5   chromedriver_mac-x64                0x00000001027999ad chromedriver_mac-x64 + 297389
6   chromedriver_mac-x64                0x00000001027c2344 chromedriver_mac-x64 + 463684
7   chromedriver_mac-x64                0x00000001028475dc chromedriver_mac-x64 + 1009116
8   chromedriver_mac-x64                0x000000010282b2b3 chromedriver_mac-x64 + 893619
9   chromedriver_mac-x64                0x00000001027f5eb9 chromedriver_mac-x64 + 675513
10  chromedriver_mac-x64                0x00000001027f70ee chromedriver_mac-x64 + 680174
11  chromedriver_mac-x64                0x0000000102bdd819 chromedriver_mac-x64 + 4769817
12  chromedriver_mac-x64                0x0000000102be2893 chromedriver_mac-x64 + 4790419
13  chromedriver_mac-x64                0x0000000102be966e chromedriver_mac-x64 + 4818542
14  chromedriver_mac-x64                0x0000000102be35bd chromedriver_mac-x64 + 4793789
15  chromedriver_mac-x64                0x0000000102bb598c chromedriver_mac-x64 + 4606348
16  chromedriver_mac-x64                0x0000000102c01b78 chromedriver_mac-x64 + 4918136
17  chromedriver_mac-x64                0x0000000102c01d30 chromedriver_mac-x64 + 4918576
18  chromedriver_mac-x64                0x0000000102c1285e chromedriver_mac-x64 + 4986974
19  libsystem_pthread.dylib             0x00007ff809b371d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff809b32bd3 thread_start + 15

--------------------------------------------------
Submit the error here: https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/new?template=bug_report.yml
--------------------------------------------------

### Environment

macOS 14.0, M2 Macbook
Using pip install method: yes
this was on my first run of the script

I am currently using another trakt sync method (https://github.com/josh/imdb-trakt-sync) which expires every 3 months, so ratings and watchlists are up to date. But want to use yours instead since it doesn't expire (at least I think it doesn't).

**Comment by RileyXX** [comment]
Hi sorry for the late reply. There have been several improvements with driver handling since you last posted this. Can you confirm if you are still having issues in the latest version? [v3.3.0](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v3.3.0) Thanks
