### ISSUE TITLE
Getting error when synching 

### ISSUE THREAD

**Issue by fkdraeb** [RileyXX/IMDB-Trakt-Syncer#98]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

While doing the sync I got a error when starting the webdriver. I retried the command and got the same stacktrace.

```
--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 67, in main
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/p0w/trakt-imdb/IMDB-Trakt-Syncer/path/to/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: cannot find Chrome binary
Stacktrace:
#0 0x562ec2bbc6aa <unknown>
#1 0x562ec289f0dc <unknown>
#2 0x562ec28d22cf <unknown>
#3 0x562ec28d043b <unknown>
#4 0x562ec291aef9 <unknown>
#5 0x562ec290e613 <unknown>
#6 0x562ec28de4f7 <unknown>
#7 0x562ec28dee4e <unknown>
#8 0x562ec2b8287b <unknown>
#9 0x562ec2b86921 <unknown>
#10 0x562ec2b6e36e <unknown>
#11 0x562ec2b87482 <unknown>
#12 0x562ec2b52ccf <unknown>
#13 0x562ec2bac0a8 <unknown>
#14 0x562ec2bac280 <unknown>
#15 0x562ec2bbb7dc <unknown>
#16 0x7f6daeb03a94 <unknown>
#17 0x7f6daeb90c3c <unknown>
```

### Environment

OS: Ubuntu 24.04 (WSL)

**Comment by RileyXX** [comment]
Sorry for the late response. Looks like the script can't find the chrome binary (your chrome install executable). OS may not be supported. I can look into this more when I get some time.

**Comment by RileyXX** [comment]
This might be fixed in v3.3.0. The script uses new methods to handle chrome browser and chromedriver internally. I recommend giving it a try and see how it goes.
